Setup indentation 4
pets-oss/pets-back pull request #104
Opened 2021-02-28 09:54 UTC by AzisK

Additionally setup warning for double quotes

2021-02-28 14:05 UTC, ignasposka requested changes
Requesting changes, because in some places readability looks much worse at least for me. If you think opposite let's discuss.

2021-02-28 14:05 UTC, ignasposka commented on src/index.ts
> +import {
IMHO this looks much worse than a straight line as before. Maybe we could allow few characters more to preserve such imports inline? Previous line is not that long I think 🤔

2021-02-28 14:05 UTC, ignasposka commented on src/schema/resolvers/animal.ts
> +    Query: {
Same here, looks much less readable when split into multiple lines 😖

2021-02-28 14:33 UTC, AzisK commented on src/index.ts
> +import {
I used a VS Code plugin 'Beautify' to auto-reindent all the lines. It has also did this "beauty" according to him. I did not find this important to bring it back to one line. If you think that is important, I can bring it back to the old version

2021-02-28 14:33 UTC, AzisK commented on src/schema/resolvers/animal.ts
> +    Query: {
I used a VS Code plugin "Beautify" to auto-reindent all the lines. It has also did this "beauty" according to him. I did not find this important to bring it back to one line. If you think that is important, I can bring it back to the old version

2021-02-28 18:32 UTC, ignasposka commented on src/index.ts
> +import {
I think you should adjust `Beautify` settings to allow longer lines, or just bring the old formatting back.

2021-03-02 11:17 UTC, ignasposka approved these changes
Just fix all places such I noted in my comment and you're good to merge.

2021-03-02 11:17 UTC, ignasposka commented on test/user.grapqhl.test.ts
> +                const {
This multiline split also looks unnecessary.

2021-03-02 12:16 UTC, AzisK commented on test/user.grapqhl.test.ts
> +                const {
It does not seem possible with prettier, so I will look into other formatters

2021-03-02 19:58 UTC, psaulenas approved these changes

2021-03-04 19:04 UTC, merged