Cloudinary integration (closes #30)
pets-oss/pets-back pull request #128
Opened 2021-03-19 11:26 UTC by JustasBelevicius

2021-03-21 12:08 UTC, ignasposka requested changes
Maybe there is a way to test photo upload without directly interacting with Cloudinary? To mock it or something?

2021-03-21 15:18 UTC, JustasBelevicius commented on src/schema/resolvers/animal.ts
> +            if (process.env.CLOUDINARY_DISABLED !== 'false') {
Damn, good catch

2021-03-21 15:52 UTC, JustasBelevicius commented on src/services/cloudinary.ts
> +                            resolve(undefined);
I believe it is better to fail silently here, reject would force the users of this method to wrap the function in a try/catch block.

2021-03-22 07:26 UTC, ignasposka approved these changes

2021-03-22 07:41 UTC, merged