#12 Create DB tables according to class diagram
pets-oss/pets-back pull request #17
Opened 2020-12-05 17:29 UTC by AzisK

Added tables with sample data according to ER diagram. Few notes:

a) I could not go with table name "user" because this is a reserved word in postgresql. Now it's a little weird that all tables are in singular except one is in plural. Should we rename users or go with plural names for tables?
b) Few-word column naming is different. Sometimes it's snake_case (full_name, registration_no etc.) and sometimes it's camelCase (dateTime, imageUrl etc.). I believe we should unify the style.
c) From the diagram I did not understand the data type of eventType. Should it be an enum? For now I just made it a VARCHAR to be more flexible since we do not know all the possible event types and they might change in the future.
d) We might need a time-zone aware timestamp but I am not sure about it at the moment
e) I believe we should add a "modtime" column to users, animal, organization tables since they might be modified and modtime would be good to track and help debug what happened
f) We will ammend enum values later, now I do not know them. More about them:
https://www.postgresql.org/docs/9.1/functions-enum.html
https://dzone.com/articles/when-you-should-and-should-not

2020-12-05 17:36 UTC, AzisK commented
To compare with ER diagram, check here https://github.com/pets-oss/pets-back/blob/bdfa6f4761d46fc2ca81ad88d850ff6b3219e1db/docs/GIS%20ERD.pdf

2020-12-07 07:26 UTC, ignasposka commented
a) Let's stay with singulars, just rename user table to gis_user or app_user.
b) I agree with that, let's use snake_case
c) It should be enum, because it's "type", my bad not specifying it in diagram :(
d) I think we should decide now, because it would be messy to adjust that later while we have already dates in DB
e) That's a good idea, let's add it!
f) Sure

2020-12-07 09:21 UTC, ignasposka commented
@AzisK regarding time zone aware timestamp, I don't think we need such. My suggestion would be to always use UTC time in DB and adjust time on client side according to user's timezone.

2020-12-07 10:58 UTC, AzisK commented
@ignasposka I also do not see a reason to have a time-zone aware timestamp in the database, let's go with the usual timestamp

2020-12-07 11:58 UTC, AzisK commented
Applied the changes according to comments

2020-12-07 12:32 UTC, JustasBelevicius approved these changes
Looks good, as @ignasposka mentioned, use enums for types.

2020-12-07 13:02 UTC, psaulenas requested changes
That is a good start! Left a few suggestions about how it could improve

2020-12-07 13:02 UTC, psaulenas commented on database/schema.sql
> +    organization SMALLINT REFERENCES organization(id)
Same with the type

2020-12-07 13:02 UTC, psaulenas commented on database/schema.sql
> +    animal INTEGER REFERENCES animal(id),
Same with the type

2020-12-07 13:02 UTC, psaulenas commented on database/schema.sql
> +    organization SMALLINT REFERENCES organization(id),
Same with the type

2020-12-07 13:02 UTC, psaulenas commented on database/schema.sql
> +    animal INTEGER REFERENCES animal(id),
Same with the type

2020-12-07 13:02 UTC, psaulenas commented on database/schema.sql
> +    organization SMALLINT REFERENCES organization(id),
Same with the type

2020-12-07 13:02 UTC, AzisK commented
@JustasBelevicius this has been already implemented. By the way, I used different event enums. Since they are for different tables, I believe it makes sense to separate them
`CREATE type event_general AS ENUM ('birthday', 'addoption', 'getting petted', 'going for a walk');`
`CREATE type event_medical AS ENUM ('deworm', 'vaccinate', 'surgery', 'antibiotics');`

2020-12-07 13:04 UTC, JustasBelevicius commented on database/data.sql
> +UPDATE app_user SET email = 'black@mamba.lt' WHERE id = 'dhjbwau74a6';
Nothing discriminating in this context, but sure, better safe than sorry

2020-12-07 13:05 UTC, AzisK commented on database/data.sql
> +UPDATE app_user SET email = 'black@mamba.lt' WHERE id = 'dhjbwau74a6';
With Black Mamba I was referring to Kobe Bryant but alright, I will change that since it could be misunderstood

2020-12-07 13:06 UTC, AzisK commented on database/schema.sql
> +    id SMALLSERIAL PRIMARY KEY,
This was done according to ER diagram. I thought it makes sense since we should not have so many organizations but we can never know. What do you think @psaulenas @ignasposka ?

2020-12-07 13:08 UTC, AzisK commented on database/schema.sql
> +    full_name VARCHAR(256),
I like this idea. @ignasposka do you agree?

2020-12-07 13:08 UTC, JustasBelevicius commented on database/schema.sql
> +CREATE type event_general AS ENUM ('birthday', 'addoption', 'getting petted', 'going for a walk');
Misstype: `adoption`.
Are "getting petted", "going for a walk" valid event types? I don't see people registering such events into the system.

2020-12-07 13:09 UTC, AzisK commented on database/schema.sql
> +    address VARCHAR(512),
I like this idea. What do you think @ignasposka ?

2020-12-07 13:16 UTC, AzisK commented on database/schema.sql
> +CREATE type event_general AS ENUM ('birthday', 'addoption', 'getting petted', 'going for a walk');
Thanks for the typo. These are just dummy values for now, I don't know them. We can ammend them later.

2020-12-07 13:37 UTC, AzisK commented on database/schema.sql
> +    organization SMALLINT REFERENCES organization(id),
It is not the same. However, their range to the positive side is the same. 
From https://www.tutorialspoint.com/postgresql/postgresql_data_types.htm
`smallserial | 2 bytes | small autoincrementing integer | 1 to 32767`
`smallint | 2 bytes | small-range integer | -32768 to +32767`

We can go with SMALLSERIAL. I did not go with SMALLSERIAL because it is self-incrementing and we do not need that. The difference here would be that with small serial we could not have NULL organization values for app_user

I tried out the behaviour. if I add
`INSERT INTO app_user (id, username, full_name, email) VALUES ('dhjbw3234au74a6', 'Svx', 'Sveikas', 'svx@svx.lt');`
a) with SMALLSERIAL for this record I get organization=4 having 4 organizations (it will get the latest organization id with current setup). If I do it later (with different app_user id), it prevents the insertion. It also prevents insertion having organization=NULL
b) while with SMALLINT for this record I get organization=NULL

SMALLSERIAL behaviour is a little weird and unexpected to me. What do you think?

2020-12-07 13:49 UTC, psaulenas commented on database/data.sql
> +UPDATE app_user SET email = 'black@mamba.lt' WHERE id = 'dhjbwau74a6';
We should avoid terminology, words that could be sensitive in terms of discrimination as our company is against that and had the initiative to remove similar terminology

2020-12-07 13:52 UTC, psaulenas commented on database/schema.sql
> +    id SMALLSERIAL PRIMARY KEY,
I think we shouldn't restrict ourselves, maybe we won't reach the limit, maybe we will. It won't save us a lot of space or would help, for example, have better performance

2020-12-07 13:55 UTC, AzisK commented on database/data.sql
> +UPDATE app_user SET email = 'black@mamba.lt' WHERE id = 'dhjbwau74a6';
I agree with that, not just company but we are so as well

2020-12-07 14:21 UTC, psaulenas approved these changes
GJ!

2020-12-07 14:21 UTC, psaulenas commented on database/schema.sql
> +    organization SMALLINT REFERENCES organization(id),
I see. It is a specific data type. Let's leave `SMALLINT`s in foreign keys

2020-12-07 14:21 UTC, psaulenas commented on database/data.sql
> +CREATE EXTENSION moddatetime;
Maybe separate words with `_` for consistency?

2020-12-07 17:36 UTC, AzisK commented on database/data.sql
> +CREATE EXTENSION moddatetime;
That's a good point. I even wrote `modtime` for the column. When I think of it, it's 2 words. `moddatetime` is actually 3 words, should it be mod_date_time? What do you think?

2020-12-07 17:41 UTC, AzisK commented on database/data.sql
> +CREATE TRIGGER organization_moddatetime
I agree with that. It's part of the definition of the tables and their behavior. Move id to schema.sql

2020-12-07 17:51 UTC, AzisK commented on database/schema.sql
> +    full_name VARCHAR(256),
Separated it to "name" and "surname". @ignasposka Let me know if you agree also FYI if we are going to update the ER diagram

2020-12-07 17:57 UTC, AzisK commented on database/schema.sql
> +    id SMALLSERIAL PRIMARY KEY,
Changed it to SERIAL and updated the referencing foreign keys to INTEGER

2020-12-07 18:12 UTC, AzisK commented on database/data.sql
> +CREATE EXTENSION moddatetime;
Actually moddatetime is a function of Postgresql and I cannot change that https://www.postgresql.org/docs/10/contrib-spi.html#id-1.11.7.46.9 However, I renamed `modtime` to `mod_time`

2020-12-07 18:26 UTC, AzisK commented on database/schema.sql
> +    address VARCHAR(512),
Decomposed address field into country, city, street, house and flat fields
```sql
CREATE TABLE organization (
    id SERIAL PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    country VARCHAR(512),
    city VARCHAR(128),
    street VARCHAR(128),
    house VARCHAR(32),
    flat VARCHAR(32),
    phone VARCHAR(64),
    mod_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
```
https://github.com/pets-oss/pets-back/commit/0e81f53163ca5fcdac7b49e8b6a38b2286a627e8

2020-12-07 18:31 UTC, ignasposka commented on database/schema.sql
> +    id SMALLSERIAL PRIMARY KEY,
Sure, you can change it to `SERIAL`, I just chose `SMALLSERIAL` because I don't think we might have so many organisations.

2020-12-07 18:32 UTC, ignasposka commented on database/schema.sql
> +    address VARCHAR(512),
I like this ideas, but in this case I would suggest creating separate table `address` which would hold these three values.

2020-12-07 18:33 UTC, ignasposka commented on database/schema.sql
> +    full_name VARCHAR(256),
Yes, I agree. I can update ER diagram after we settle with this PR :)

2020-12-07 18:38 UTC, AzisK commented
Made changes according to comments. Few fields that we could add with this PR or in the future (most are suggestions from dad):
- animal 
    - add color field
    - add weight field
    - breed (now we have species but this is more for whether it is a dog or a cat, I believe, and not if it's a Chihuahua or Alaskan Malamute)
    - registration date in the shelter. This could be very important because I heard rumors that animals in some shelters are kept only for a certain period before euthanasia
    - allergy maybe?

2020-12-07 18:41 UTC, ignasposka commented on database/schema.sql
> +    organization SMALLINT REFERENCES organization(id),
According to this discussion https://www.postgresql.org/message-id/42A091A7.4050802@commandprompt.com using `INTEGER` should be fine as `SERIAL` is a pseudo type for `INTEGER`.

2020-12-07 18:43 UTC, ignasposka commented
> @ignasposka I also do not see a reason to have a time-zone aware timestamp in the database, let's go with the usual timestamp

But then we have to set DB server and backend always use UTC.

2020-12-07 18:46 UTC, AzisK commented
> > @ignasposka I also do not see a reason to have a time-zone aware timestamp in the database, let's go with the usual timestamp
> 
> But then we have to set DB server and backend always use UTC.

We should also communicate that to front-end if they are somehow going to send the date_time

2020-12-07 18:50 UTC, AzisK commented on database/schema.sql
> +    address VARCHAR(512),
Can we kept it in one table for simplicity for now?

2020-12-07 18:55 UTC, AzisK commented on database/schema.sql
> +    address VARCHAR(512),
Actually I have to re-say not to confuse you. I didn't mean to say "for now". That would not be so smart since we can decide on this now. I meant that I would rather have it here for simplicity but let me know if there is something I am missing

2020-12-07 19:31 UTC, AzisK commented
> Made changes according to comments. Few fields that we could add with this PR or in the future (most are suggestions from dad):
> 
>     * animal
>       
>       * add color field
>       * add weight field
>       * breed (now we have species but this is more for whether it is a dog or a cat, I believe, and not if it's a Chihuahua or Alaskan Malamute)
>       * registration date in the shelter. This could be very important because I heard rumors that animals in some shelters are kept only for a certain period before euthanasia
>       * allergy maybe?

Added these fields. Please share if you see more proper data-types for these fields https://github.com/pets-oss/pets-back/pull/17/commits/08d545098315ec959b0bf2c181ca7531f26c6195

2020-12-08 06:58 UTC, ignasposka commented on database/schema.sql
> +    address VARCHAR(512),
Alright, that works for me, I don't have a strong opinion for this case anyway.

2020-12-08 07:03 UTC, ignasposka approved these changes
Good job, thanks!

2020-12-08 08:30 UTC, merged