#152, #140, #141 animal gallery, animal favorite, modtime to animal microchip
pets-oss/pets-back pull request #170
Opened 2021-04-06 19:21 UTC by rimantepomeckyte

2021-04-06 19:31 UTC, JustasBelevicius reviewed
Well done! I have left some comments under specific lines.

Besides that, it would also be useful adding fake data for favourite and gallery tables.

P.S. In my opinion, it would've been better to have 3 different commits for each issue (can still be under the same pull request). That way a specific change can be easily reverted if the need arises.

2021-04-06 19:31 UTC, JustasBelevicius commented on database/1-schema.sql
> +    url VARCHAR(255)
Looking at the previous implementation in the animals table, the size used there was 2048, it would be best keeping it consistent.

2021-04-06 19:31 UTC, JustasBelevicius commented on database/1-schema.sql
> +PRIMARY KEY (user_id, animal_id)
formatting: missing tabs

2021-04-07 21:19 UTC, JustasBelevicius requested changes
Let's focus on the `animal_gallery` functionality with this PR. There are a few improvements you should do before we merge it:

- [ ] Add `mod_time` field and trigger for the `animal_gallery` field
- [ ] Update the size of the `url` to be consistent with other url fields (check `animals` table)
- [ ] Add fake data for this table.

2021-04-07 21:19 UTC, JustasBelevicius commented on database/1-schema.sql
> +    url VARCHAR(255)
Looking at all the issues where we are adding mod_times, we should actually add one here as well. Don't create to add a trigger for it.

2021-04-08 08:00 UTC, JustasBelevicius approved these changes
Looks good, I've selected other PRs for animal favorite and animal microchip, so let's wait until those are merged, and then merge this one in.

2021-04-08 12:08 UTC, AzisK requested changes
Good job in general! I left a few comments for possible improvements

2021-04-08 12:08 UTC, AzisK commented on .gitignore
> +package-lock.json
From what I know and remember, we should not have `package-lock.json` in `.gitignore`. This file speeds up the deployment process and if new libraries are added, they should be commited. Am I right, @JustasBelevicius?

2021-04-08 12:08 UTC, AzisK commented on database/1-schema.sql
> +user_id VARCHAR(255) REFERENCES app_user(id) ON DELETE CASCADE NOT NULL,
I know this pull request focuses on animal_gallery but if  animal_favorite differs from main, then conflicts would need to be resolved for animal_favorite table. Thus, it's good to align the spacing here as well

2021-04-08 12:10 UTC, JustasBelevicius commented on .gitignore
> +package-lock.json
Lets ignore it. If we add new packages we will force push the package-lock.json file, this will prevent others from pushing package-lock.json changes accidentally

2021-04-08 12:11 UTC, JustasBelevicius commented on database/1-schema.sql
> +user_id VARCHAR(255) REFERENCES app_user(id) ON DELETE CASCADE NOT NULL,
Not a blocker, will be resolved before merging, when resolving conflicts

2021-04-08 12:23 UTC, rimantepomeckyte commented on database/1-schema.sql
> +user_id VARCHAR(255) REFERENCES app_user(id) ON DELETE CASCADE NOT NULL,
So for now i should leave it or fix it?

2021-04-08 12:36 UTC, AzisK commented on database/1-schema.sql
> +user_id VARCHAR(255) REFERENCES app_user(id) ON DELETE CASCADE NOT NULL,
I believe you could leave it then. We can resolve this when resolving the conflict.

2021-04-08 12:47 UTC, rimantepomeckyte commented on database/1-schema.sql
> +user_id VARCHAR(255) REFERENCES app_user(id) ON DELETE CASCADE NOT NULL,
Ok, thanks

2021-04-08 13:08 UTC, AzisK approved these changes

2021-04-09 10:26 UTC, merged