144 sheltered animal stats
pets-oss/pets-back pull request #174
Opened 2021-04-07 15:04 UTC by mindra

Solving issue https://github.com/pets-oss/pets-back/issues/144
Would be nice to get  feedback

2021-04-10 09:37 UTC, AzisK requested changes
That's a good start. I left some comments for improvements.

This is a bit shorter solution that I propose (it's possible to come up with an even shorter one)

```sql
SELECT 
	EXTRACT(YEAR FROM aef.date_time) * 100 + EXTRACT(MONTH FROM aef.date_time) AS year_month,
	st."translation", 
	'found' AS circumstance,
	COUNT(*) cnt
FROM animal_event_found aef 
JOIN animal_details ad
    ON aef.animal_id = ad.animal_id 
JOIN breed b 
    ON ad.breed_id = b.id 
JOIN (SELECT * FROM species_translation WHERE language = 'lt') st 
    ON b."species" = st."species" 
GROUP by st."translation", year_month
UNION ALL
SELECT 
    EXTRACT(YEAR FROM agw.date_time) * 100 + EXTRACT(MONTH FROM agw.date_time) AS year_month,
	st."translation", 
	'given away' AS circumstance,
	COUNT(*) cnt
FROM animal_event_given_away agw 
JOIN animal_details ad
    ON agw.animal_id = ad.animal_id 
JOIN breed b 
    ON ad.breed_id = b.id 
JOIN (SELECT * FROM species_translation WHERE language = 'lt') st  
    ON b."species" = st."species" 
GROUP BY st."translation", year_month
ORDER BY year_month;
```

2021-04-10 09:37 UTC, AzisK commented on database/4-reports.sql
> +GROUP BY to_char(aega.date_time, 'yyyymm'), ad.breed_id, a.organization
Good job on even grouping by organization. Pardon me for not specifying this in the ticket. For now we can simply return the sheltered statistics of all organizations and later we can always plug in a WHERE filter to filter by organization id

2021-04-10 09:37 UTC, AzisK commented on database/4-reports.sql
> +INNER JOIN animal_details ad ON ad.animal_id = aef.animal_id
There is no need to write `INNER JOIN` as `JOIN` is defaulted to `INNER JOIN`

2021-04-10 09:37 UTC, AzisK commented on database/4-reports.sql
> +GROUP BY to_char(aega.date_time, 'yyyymm'), ad.breed_id, a.organization
According to this ticket, we should group by species, not breed. Thus, I believe grouping by breed_id is not totally correct

2021-04-10 09:37 UTC, AzisK commented on database/4-reports.sql
> +INNER JOIN species_translation st ON st."species" = b."species"
As we have translations, we should specify the "lt" language here as well. If not and if we had more translations, we would get all of the translations

2021-04-20 06:05 UTC, AzisK commented
@mindra are you going to update the code?

2021-04-20 06:18 UTC, mindra commented
I'll do my best to push updates later today

2021-04-20 19:58 UTC, mindra commented on database/4-reports.sql
> +INNER JOIN animal_details ad ON ad.animal_id = aef.animal_id
Updated

2021-04-20 19:58 UTC, mindra commented on database/4-reports.sql
> +INNER JOIN species_translation st ON st."species" = b."species"
Updated

2021-04-20 19:58 UTC, mindra commented on database/4-reports.sql
> +GROUP BY to_char(aega.date_time, 'yyyymm'), ad.breed_id, a.organization
Updated

2021-04-22 20:28 UTC, AzisK approved these changes
LGTM

2021-04-22 20:28 UTC, merged