141 | Added animal favorite table
pets-oss/pets-back pull request #177
Opened 2021-04-07 19:43 UTC by mindra

Added table to store users favorite animals
https://github.com/pets-oss/pets-back/issues/141

2021-04-07 21:10 UTC, JustasBelevicius requested changes
Well done! I've added some comments.

2021-04-07 21:10 UTC, JustasBelevicius commented on database/1-schema.sql
> +    mod_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
Brilliant idea!

You should add a trigger so that the mod_time is changed on entry  update.

2021-04-07 21:10 UTC, JustasBelevicius commented on database/3-fake-data.sql
> +-- ANIMAL FAVOURITE
nit: favorite - american english, favourite - british english. I have no preferenced, but it would be better to stay consistent.

FYI: nit is short for nitpicking - nit comments are nice to have, but are not required for a successful merge

2021-04-08 10:48 UTC, mindra commented on database/1-schema.sql
> +    mod_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
Added  trigger

2021-04-08 10:49 UTC, mindra commented on database/3-fake-data.sql
> +-- ANIMAL FAVOURITE
Fixed spelling to follow consistency.

2021-04-08 11:59 UTC, AzisK requested changes
I think that a missing semicolon will not go well inside the migration scripts but else looks good!

2021-04-08 11:59 UTC, AzisK commented on database/1-schema.sql
> +CREATE TRIGGER animal_favorite_mod_time BEFORE UPDATE ON animal_favorite
NAB (not a blocker). I would move this trigger after the initial animal-properties triggers to represent the same order as the table creations

2021-04-08 11:59 UTC, AzisK commented on database/3-fake-data.sql
> +('278y2378ryb', 3)
I believe a semicolon `;` is missing here

2021-04-08 12:01 UTC, JustasBelevicius approved these changes

2021-04-09 09:49 UTC, mindra commented on database/3-fake-data.sql
> +('278y2378ryb', 3)
As this was last, migration script did  not failed (at least for me :)), but yeah in the future that could be an issue. Fixed this.

2021-04-09 09:54 UTC, AzisK approved these changes

2021-04-09 09:54 UTC, merged