#151 normalize address in animal event found table
pets-oss/pets-back pull request #178
Opened 2021-04-08 07:43 UTC by pergaliuke

2021-04-08 11:18 UTC, AzisK requested changes
Good job! I agree this is more informative but I suggest to shorten the column names for simplicity

2021-04-08 11:33 UTC, pergaliuke commented on database/1-schema.sql
> +    address_street VARCHAR(255) NOT NULL,
done

2021-04-08 11:47 UTC, AzisK approved these changes

2021-04-09 07:14 UTC, ignasposka approved these changes

2021-04-09 07:21 UTC, merged