#145 get rid of delete time in organization table
pets-oss/pets-back pull request #179
Opened 2021-04-08 08:22 UTC by kostamir

2021-04-08 18:43 UTC, AzisK requested changes
Well done. It looks good. Left a comment for a possible improvement and a question

2021-04-08 18:43 UTC, AzisK commented on src/sql-queries/organization.ts
> +import { select, insert, update, delete as remove } from 'sql-bricks-postgres';
Why rename delete to remove?

2021-04-08 18:43 UTC, AzisK commented on src/sql-queries/organization.ts
> +    select().from('organization').where({}).toParams();
I believe we can skip the `where` part?

2021-04-09 06:50 UTC, kostamir commented on src/sql-queries/organization.ts
> +    select().from('organization').where({}).toParams();
Done.

2021-04-09 06:51 UTC, kostamir commented on src/sql-queries/organization.ts
> +import { select, insert, update, delete as remove } from 'sql-bricks-postgres';
Tried to use delete as is but vscode thew an error so we came up with this workaround.

2021-04-09 07:01 UTC, AzisK approved these changes

2021-04-09 07:10 UTC, JBK91 commented on src/sql-queries/organization.ts
> +import { select, insert, update, delete as remove } from 'sql-bricks-postgres';
Because delete is reserved JS keyword

2021-04-09 07:16 UTC, ignasposka approved these changes

2021-04-09 07:31 UTC, merged