#188 expand /status endpoint with more information
pets-oss/pets-back pull request #190
Opened 2021-04-12 18:20 UTC by ieva1919

2021-04-12 19:33 UTC, lukaskairys commented on src/index.ts
> +            'status': 'ok',
status should only be ok when both database and cloudinary statuses are ok

2021-04-12 20:48 UTC, psaulenas commented on src/getVersion.ts
> +    const result = await fs.promises.readFile('package.json', 'utf8')
You could get the version using import from `package.json`
```js
import { version } from '../package.json';
```

Then probably this separate file (function) not needed

2021-04-13 09:30 UTC, ignasposka requested changes

2021-04-13 09:30 UTC, ignasposka commented on src/index.ts
> +        let isDataBasedActive = false
Typo in word "Database".

2021-04-13 09:30 UTC, ignasposka commented on src/index.ts
> +        let isCloudinaryClient = false
It should be called `isCloudinaryClientActive`.

2021-04-13 09:30 UTC, ignasposka commented on src/index.ts
> +        let isVersion = ''
It should be called just `version`.

2021-04-13 09:30 UTC, ignasposka commented on src/index.ts
> +                text: 'select true as ok'
SQL keywords have convention to be uppercase. Therefore it should be `SELECT true AS ok`.

2021-04-13 09:30 UTC, ignasposka commented on src/services/cloudinary.ts
> +        const response = await cloudinary.api.ping()
Missing semicolon in the end of a line.

2021-04-13 12:17 UTC, ignasposka commented on src/index.ts
> +            isDataBasedActive = results.rows[0].ok
This access chain could lead to null pointer exception. Use optional chaining to prevent that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

It would look like `results.rows[0]?.ok`

2021-04-13 17:43 UTC, ieva1919 commented on src/getVersion.ts
> +    const result = await fs.promises.readFile('package.json', 'utf8')
I attempted to import this but I have an error Cannot find module '../package.json'. What I have to change for this import to work?

2021-04-13 18:11 UTC, psaulenas commented on src/getVersion.ts
> +    const result = await fs.promises.readFile('package.json', 'utf8')
You need to add `resolveJsonModule: true` in the tsconfig file

2021-04-14 04:27 UTC, ieva1919 commented on src/getVersion.ts
> +    const result = await fs.promises.readFile('package.json', 'utf8')
Thank you, now it works.

2021-04-14 14:39 UTC, ignasposka approved these changes
Please fix code according to my comments and it will be good to merge :)

2021-04-14 14:39 UTC, ignasposka commented on src/index.ts
> +        let isDatabaseActive = false
No semicolon in the end of the line. Please apply this for all lines where required.

2021-04-14 14:39 UTC, ignasposka commented on src/index.ts
> +                text: 'select true as OK'
SQL keywords have convention to be uppercase. Therefore it should be `SELECT true AS ok`.

2021-04-14 14:42 UTC, ignasposka commented
Furthermore, I didn't notice code conflicts. Please fix them.

2021-04-18 16:28 UTC, merged