Feature/#131 add mutations for former animal owner
pets-oss/pets-back pull request #212
Opened 2021-04-27 20:35 UTC by pergaliuke

Added scalars Name, Surname, Phone.
Added mutations for former animal owner.
Added tests for mutations.
Minor Fix in former_animal_owner table.

I am not sure if I placed scalars in a correct folder or if my DRY approach was good.

I am little bit confused with required fields, does it mean not null? I might have made a mistake there.

2021-05-15 08:46 UTC, ignasposka requested changes

2021-05-15 08:46 UTC, ignasposka commented on src/schema/scalars/getStringScalarWithValidation.ts
> +    max?: number,
Let's use `| null` to be consistent with other interfaces in Petbook project.

2021-05-15 08:46 UTC, ignasposka commented on src/schema/scalars/scalars.ts
> +    name: 'Phone', pattern: /^\+3706\d{7}$/
I think we should move country code to a config file, by doing that we would let use system not only with Lithuanian phone numbers.

2021-05-15 08:46 UTC, ignasposka commented on src/schema/typeDefs/formerAnimalOwner.graphql
> +    name: Name!
Name shouldn't be required during update, maybe user would want to change some other fields and leave name untouched.

2021-05-15 08:46 UTC, ignasposka commented on src/sql-queries/formerAnimalOwner.ts
> +const returnFields = '*';
I think moving `*` to a variable is pointless here, because it's well known SQL character, furthermore it would be more readable if it would be in a query.

2021-05-15 08:46 UTC, ignasposka commented on test/formerAnimalOwner.graphql.test.ts
> +                    id: 2,
I would suggest to save id from create mutation response and use it here to update freshly created entry. By that we always would be sure that id exist.

2021-05-15 08:47 UTC, ignasposka commented
> I am little bit confused with required fields, does it mean not null? I might have made a mistake there.

Yes, required field means it won't be null.

2021-05-18 10:45 UTC, pergaliuke commented on src/schema/scalars/getStringScalarWithValidation.ts
> +    max?: number,
```
src/schema/scalars/scalars.ts(5,37): error TS2345: Argument of type '{ name: string; pattern: RegExp; }' is not assignable to parameter of type 'Config'.
  Property 'max' is missing in type '{ name: string; pattern: RegExp; }' but required in type 'Config'.
```

`max: number | null ` will not compile with optional fields. If we change optional(?) to | null or | undefined,  field becomes **required** with possible values `null `or `undefined`.

`max?: number` is more like `max: number | undefined` in **strict** TypeScript, but not exactly due to required or not.

More information:
https://www.typescriptlang.org/docs/handbook/2/objects.html#property-modifiers.

2021-05-19 10:30 UTC, ignasposka commented on src/schema/scalars/getStringScalarWithValidation.ts
> +    max?: number,
That's a good point, thanks for clarifying.

2021-05-20 11:42 UTC, pergaliuke commented on test/formerAnimalOwner.graphql.test.ts
> +                    id: 2,
Done

2021-05-20 11:43 UTC, pergaliuke commented on src/schema/typeDefs/formerAnimalOwner.graphql
> +    name: Name!
Fixed.

2021-05-20 11:50 UTC, pergaliuke commented on src/schema/scalars/scalars.ts
> +    name: 'Phone', pattern: /^\+3706\d{7}$/
Changed, please look at this again. Pattern was : /^\+3706\d{7}$/ , now pattern allows more digits than Lithuania has after country code. It is ok?

2021-05-20 19:42 UTC, ignasposka requested changes

2021-05-20 19:42 UTC, ignasposka commented on src/schema/scalars/getStringScalarWithValidation.ts
> +            throw new Error('Value must be a string');
Let's throw `ValidationError` instead of `Error`.

2021-05-20 19:42 UTC, ignasposka commented on src/schema/scalars/getStringScalarWithValidation.ts
> +const validate = (value: unknown, config: Config) => {
I think we should add test for this validation.

2021-05-20 19:42 UTC, ignasposka commented on src/schema/scalars/scalars.ts
> +    pattern: new RegExp(`^\\+${config.phoneCountryCode}\\d{8,10}$`)
Add default country code fallback in case one from config is missing.

2021-05-20 19:42 UTC, ignasposka commented on src/config.ts
> +export default {
I would have put this into some kind of `.env` file. But I'm not sure if that's a right way or not. @JustasBelevicius @AzisK @JBK91 @psaulenas  what do you think?

2021-05-20 20:03 UTC, psaulenas commented on src/config.ts
> +export default {
I don't think this should be stored in the environment variables. I believe we should think about an easily extensible solution. Also, we should support other countries phone formats but probably default to `LT`. So, my suggestion is to have a configuration something like:

```js
export phoneFormatByCountry {
 lt: '370'
 lv: '371'
}
```

Probably, you will get a lint error because there is only one export in this file at the moment. However, I would disable that lint error. And personally, I don't like that lint rule.

2021-05-21 18:44 UTC, ignasposka requested changes

2021-05-21 18:44 UTC, ignasposka commented on src/config.ts
> +export default {
Alright, I like Paulius suggestion about the format.
But for default exports let's keep them consistent - let's have default one if it's a single export.

2021-05-25 19:47 UTC, ignasposka approved these changes
Looks good. You were asking about testing case while passing non string value into string scalar, I think you can add this test case expecting it to throw `ValidationError`, I don't see a problem here.

2021-05-26 11:52 UTC, pergaliuke commented
> Looks good. You were asking about testing case while passing non string value into string scalar, I think you can add this test case expecting it to throw `ValidationError`, I don't see a problem here.

I wanted to do something like 
const INVALID = [ 0, 3.2, true] 
I am little bit confused about about null values. It seems that null does not go through Scalar at all.

2021-05-26 16:35 UTC, AzisK approved these changes
Very good job!

2021-05-27 10:16 UTC, merged