#213 Add new fields for event DB tables
pets-oss/pets-back pull request #215
Opened 2021-05-02 19:27 UTC by LukasKri

Hey @ignasposka, I've added new fields (`author` and `mod_time`) to tables `animal_event_general`, `animal_event_medical_record`, `animal_event_found` and `animal_event_given_away`. Was I supposed to create `mod_time` triggers and add fake data as well? If no, just let me know and I will delete them.

Resolves #213.

2021-05-02 19:45 UTC, ignasposka commented
> Hey @ignasposka, I've added new fields (`author` and `mod_time`) to tables `animal_event_general`, `animal_event_medical_record`, `animal_event_found` and `animal_event_given_away`. Was I supposed to create `mod_time` triggers and add fake data as well? If no, just let me know and I will delete them.
> 
> Resolves #213.

Yes, please add triggers and add some fake data.

2021-05-02 20:19 UTC, LukasKri commented
I’ve already added them in advance, let me know if that satisfies you.

2021-05-12 08:13 UTC, JustasBelevicius requested changes

2021-05-12 08:13 UTC, JustasBelevicius commented on database/1-schema.sql
> +    author VARCHAR(255),
This should be a foreign key to the app_user table, same in other places. Probably wasn't mentioned in the spec, sorry for that!

2021-05-12 08:13 UTC, JustasBelevicius commented on database/3-fake-data.sql
> +(2, '1', 109.03, '2020-07-01', 'Registration!', 'Benas'),
Once you change the field to be a foreign key, update these as well. thanks! Same for other tables

2021-05-17 18:37 UTC, LukasKri commented on database/1-schema.sql
> +    author VARCHAR(255),
Hi @JustasBelevicius, my apologies, I should have known that myself. Have a look when you have a moment and please let me know what you think.

2021-05-19 06:01 UTC, JustasBelevicius approved these changes
Looks good to me! Only the fix needed, and then you can merge. Well done!

2021-05-19 06:24 UTC, AzisK approved these changes
GJ

2021-05-19 06:27 UTC, AzisK commented
For some reason tests are failing, please fix it

2021-05-19 17:59 UTC, LukasKri commented
Thanks guys for your feedback!

I had to update a lot of files, because new mutations was added to the tables while I was updating them and therefore new tests of those mutations were failing. I believe everything is up to date right now, could you give a final check, please?

P. S. I tried to squash my commits before pushing and do not know if I didn't mess them up.

2021-05-20 19:55 UTC, ignasposka requested changes
Just some formatting issues.

2021-05-20 19:55 UTC, ignasposka commented on src/sql-queries/animalEventFound.ts
> +export const createAnimalFoundEventQuery = (
Formatting of this function looked better previously..

2021-05-20 19:55 UTC, ignasposka commented on src/sql-queries/animalEventGivenAway.ts
> +    input: CreateGivenAwayEventInput | UpdateGivenAwayEventInput
Same with formatting.

2021-05-20 19:55 UTC, ignasposka commented on test/givenAwayEvent.graphql.test.ts
> +                const {
Let's revert this formatting change.

2021-05-20 19:55 UTC, ignasposka commented on test/givenAwayEvent.graphql.test.ts
> +                const {
Let's revert this formatting change.

2021-05-22 16:06 UTC, LukasKri commented
Hey @ignasposka, changes that were made by Prettier in `animalEventFound.ts`, `animalEventGivenAway.ts` and `givenAwayEvent.graphql.test.ts` files were reverted and because of previous merge some tests were failing again, so I had to make some changes in order to make them pass again.

2021-05-23 14:08 UTC, ignasposka approved these changes

2021-05-23 14:08 UTC, merged