#113 Add mutation for given away event
pets-oss/pets-back pull request #220
Opened 2021-05-03 14:41 UTC by pergaliuke

Added mutations createGivenAwayEvent ant updateGivenAwayEvent  with tests.

1. **date** field is yyyy-mm-dd, but in database **date_time** timestamp, should I change something?
2. Should I add check in resolver for updateGivenAwayEvent  if fields formerOwnerId and animalId **are not null**, any other additional checks needed?
3. Should I add **queries** or **delete mutation** as well?

2021-05-15 09:04 UTC, ignasposka commented
> Added mutations createGivenAwayEvent ant updateGivenAwayEvent with tests.
> 
> 1. **date** field is yyyy-mm-dd, but in database **date_time** timestamp, should I change something?
> 2. Should I add check in resolver for updateGivenAwayEvent  if fields formerOwnerId and animalId **are not null**, any other additional checks needed?
> 3. Should I add **queries** or **delete mutation** as well?

1. Let's change database field to be `DATE`. Given away time is not that important, main advantage is to know which day animal was given away.
2.  No, on update no fields should be required except from `id`. You can only check if input object contains more than one field, because there is no point of performing update operation if user providing only `id`, but no fields to update.
3. Query will be added later, as we trying to develop general query to return all types of events. If you wish you can add delete mutation as well, but we are fine to doing that in a separate issue.

2021-05-15 09:57 UTC, ignasposka requested changes
Requesting changes to change database field from `TIMESTAMP` to `DATE`

2021-05-18 07:08 UTC, pergaliuke commented
> Requesting changes to change database field from `TIMESTAMP` to `DATE`

Done.

2021-05-19 05:40 UTC, ignasposka approved these changes

2021-05-19 05:40 UTC, merged