#95 Favourite animals
pets-oss/pets-back pull request #232
Opened 2021-05-13 22:16 UTC by mantasimkus

NEED HELP ON IDENTIFYING THE CURRENT USER!!! Created GraphQL create/delete mutations and a query that retrieves all favorite animals of the current user. Resolves #95.

2021-05-15 11:19 UTC, ignasposka commented
> NEED HELP WITH IDENTIFYING THE CURRENT USER!!! Created GraphQL create/delete mutations and a query that retrieves all favorite animals of the current user. Resolves #95.

Sorry that was not yet covered. I will add some functionality to resolve current user id and will let you know when you can proceed with this PR.

2021-05-20 19:43 UTC, ignasposka commented
Sorry for blocking this PR for so long. @JustasBelevicius will try to setup required solution until Monday.

2021-05-24 10:10 UTC, ignasposka commented
@mantasimkus You can proceed with this feature as we already have a way to get user id (https://github.com/pets-oss/pets-back/commit/da4a7f791f355c7e3e2d84703032c4cfcec6bf57)

2021-05-25 05:30 UTC, ignasposka commented
Something is wrong with a diff here. Can you try to update your feature branch?

2021-05-25 08:03 UTC, JustasBelevicius commented
> Something is wrong with a diff here. Can you try to update your feature branch?

Rebased, take a look!

2021-05-25 13:50 UTC, ignasposka requested changes
I don't think whole animal object should be returned after marking or unmarking it as favourite. Let's return just animal id in case of mutation. @JustasBelevicius do you agree?

2021-05-25 13:59 UTC, JustasBelevicius commented
> I don't think whole animal object should be returned after marking or unmarking it as favourite. Let's return just animal id in case of mutation. @JustasBelevicius do you agree?

I think we would be missing the entire point of using graphql, returning entire animal is okay in my opinion, if frontend doesn't need it, they wont request it in the graphql query.

2021-05-25 20:27 UTC, mantasimkus commented on src/schema/resolvers/favoriteAnimal.ts
> +            dbResponse = await pgClient.query(
I did it in case we want to display, say, an alert message with some information about an animal which was added to the list of favorite animals. But if you don't see the need of it, I'll only return animal id.

2021-05-26 20:30 UTC, ignasposka commented on src/schema/resolvers/favoriteAnimal.ts
> +            dbResponse = await pgClient.query(
I don't think that would be the case. If it would be - animal info could be fetched separately by id.

2021-05-30 08:09 UTC, ignasposka approved these changes

2021-05-30 08:09 UTC, merged