Create a table to store all events #250
pets-oss/pets-back pull request #251
Opened 2021-05-26 10:02 UTC by linaskitm

I created a `events` table in 1-schema.sql and added FK `event_id` in these 4 tables  ( `animal_event_general` `animal_event_medical_record`  `animal_event_found` `animal_event_given_away`).   Should I add FK in others tables?

Should I do changes in src/schema/typeDefs/event.graphql by adding `eventsId: Int!`?

2021-05-26 11:06 UTC, linaskitm commented
![Screenshot 2021-05-26 140458](https://user-images.githubusercontent.com/70946988/119649527-673f3980-be2b-11eb-84f6-8ee53bc593ef.png)

Idk why I can't pass Integration Test.

2021-05-26 16:45 UTC, AzisK requested changes
Good job in general.

Did you nuke and restart your local database? I think the initialization script might have failed because other event tables have foreign key in `events` table and that one is empty.

I didn't mention in the ticket but we will get rid of `animal_event_general`, `animal_event_medical_record` etc. event tables later, so no need to add `event_id` in them. We will only have some sort of event_[type]_details tables that will have foreign keys referencing `events` table

Some fake data in `events`, even copying the same events, would be good to have as well

2021-05-26 16:45 UTC, AzisK commented on database/1-schema.sql
> -
I believe these spaces are for better readability, no need to delete them

2021-05-27 15:08 UTC, linaskitm commented
Thanks for review.
It looks like I wasn't restarted my local database in first place.
Added some fake data and did restore spaces for better readability.

2021-05-27 15:47 UTC, AzisK commented on database/1-schema.sql
> +CREATE TRIGGER organization_mod_time BEFORE
Why change?

2021-05-27 15:47 UTC, AzisK commented on database/1-schema.sql
> +CREATE TRIGGER organization_mod_time BEFORE
It's hard to follow changes this way

2021-05-27 15:47 UTC, AzisK commented on database/3-fake-data.sql
> +(5, 'LocationChange', 1.00, '2018-08-03', 'Pasikeitė laikymo vietos adresas.', 'dhjbwau74a6'),(5, 'LocationChange', 1.00, '2018-08-04', 'Pasikeitė laikymo vietos adresas.', 'afhu9w4f78');
I believe there is no need to change this as well

2021-05-27 15:47 UTC, AzisK commented on database/3-fake-data.sql
> +(4, 'Medical', 'Prophylaxis', '2020-05-21', '278y2378ryb', 'Yearly vaccine');
Good job

2021-05-28 13:10 UTC, linaskitm commented on database/1-schema.sql
> +CREATE TRIGGER organization_mod_time BEFORE
My bad.
I didn't change on purpose, I think my editor changed that after save.

2021-05-28 14:49 UTC, AzisK approved these changes

2021-05-28 14:49 UTC, AzisK commented on database/1-schema.sql
> +CREATE TRIGGER animal_mod_time BEFORE UPDATE ON animal
These spaces at the end just create unnecessary clutter in git but otherwise things look good

2021-05-30 09:07 UTC, ignasposka requested changes

2021-05-30 09:07 UTC, ignasposka commented on database/1-schema.sql
> +    group_enum event_group,
Why we cannot call it just `group` instead of `group_enum`?

2021-05-31 12:15 UTC, linaskitm commented on database/1-schema.sql
> +    group_enum event_group,
I tried call `group` but after running docker I got this syntax error:

![Screenshot 2021-05-31 151208](https://user-images.githubusercontent.com/70946988/120191492-a9e58500-c222-11eb-9a8b-42e6d01121a0.png)

I changed into  `group_enum` and worked.

2021-05-31 12:49 UTC, linaskitm commented
Should I or reviewer resolve the conflicts in `database/1-schema.sql`?

2021-05-31 13:08 UTC, AzisK commented
> Should I or reviewer resolve the conflicts in `database/1-schema.sql`?

Yes. Somebody has to if we want to merge this pull request

2021-05-31 14:24 UTC, linaskitm commented
> > Should I or reviewer resolve the conflicts in `database/1-schema.sql`?
> 
> Yes. Somebody has to if we want to merge this pull request

2021-06-01 10:37 UTC, ignasposka approved these changes

2021-06-01 10:37 UTC, merged