#72 implement animals pagination with graphql. IMPORTANT. Do not add this directly to production until..
pets-oss/pets-back pull request #252
Opened 2021-05-26 12:05 UTC by pergaliuke

2021-05-26 17:44 UTC, AzisK requested changes
Great job! Minor improvement suggested

2021-05-26 17:44 UTC, AzisK commented on src/sql-queries/animal.ts
> +    query = cursor ? query.where(reverse ? lt('id', cursor) : gt('id', cursor)) : query;
As there are a bunch of tables that have id, I believe this part should be non-ambiguous

2021-05-26 17:44 UTC, AzisK commented on src/sql-queries/animal.ts
> +    query = cursor ? query.where(reverse ? lt('id', cursor) : gt('id', cursor)) : query;
Due to that, such query failed for me. You could add a test for this

```
{
  animals(first: 2, after: "MQ==") {
    edges {
      node {
        id
        name
      }
      cursor
    }
    pageInfo{
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
```

2021-05-26 17:44 UTC, AzisK commented on src/sql-queries/animal.ts
> +    query = reverse ? query.orderBy('id DESC') : query;
I don't really want to but it seems to me that we should usually order by id ascending to be consistent and correct all the time as well

2021-05-27 07:11 UTC, AzisK approved these changes
Thumbs up!

2021-05-27 07:27 UTC, JustasBelevicius approved these changes
This is very impressive! Well done 👏 ! Wait for more reviews before merging though, there is quite a lot of logic to review.

2021-05-27 07:27 UTC, JustasBelevicius commented on test/interfaces/animalConnection.interface.ts
> +export default interface AnimalConnection extends Connection<Animal> {
I believe `export default type AnimalConnection = Connection<Animal>;` would be sufficient here.

2021-05-27 07:27 UTC, JustasBelevicius commented on src/schema/resolvers/animal.ts
> +            const hasMore = limit ? rows.length > limit : false;
nit: I would prefer `const hasMore = limit && rows.length > limit;` but that's just my preference

2021-05-27 07:27 UTC, JustasBelevicius commented on test/interfaces/connection.interface.ts
> +    startCursor : string
nit: spaces before `:` are not required.

2021-05-27 09:42 UTC, pergaliuke commented
Now it returns correct results with first: 0 or last: 0 as well.

2021-05-27 09:57 UTC, AzisK commented
> Now it returns correct results with first: 0 or last: 0 as well.

What does it return in this case?

2021-05-27 10:07 UTC, pergaliuke commented
> > Now it returns correct results with first: 0 or last: 0 as well.
> 
> What does it return in this case?

```
{
  animals(first: 0) {
    ...
  }
}
```
```
{
  "data": {
    "animals": {
      "edges": [],
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
        "startCursor": null,
        "endCursor": null
      }
    }
  }
}
```

```
{
  animals(last: 0) {
    ...
  }
}
```
```
{
  "data": {
    "animals": {
      "edges": [],
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": true,
        "startCursor": null,
        "endCursor": null
      }
    }
  }
}
```

2021-05-28 12:25 UTC, ignasposka requested changes
Good job! Just added some small suggestions.

2021-05-28 12:25 UTC, ignasposka commented on test/interfaces/connection.interface.ts
> +    edges: Edge<T>[]
Missing semicolons. @JustasBelevicius Can we add this to eslint rules?

2021-05-28 12:25 UTC, ignasposka commented on src/schema/typeDefs/animal.graphql
> +        after: String,
I think it would be more clear if parameters would go in the following order: `after`, `before`, `first`, `last`.

2021-05-28 12:43 UTC, AzisK commented on src/schema/typeDefs/animal.graphql
> +        after: String,
I wouldn't necessarily agree because looking at SWAPI it's this way https://graphql.org/swapi-graphql/. However, looking at Githubs API it's as you suggest https://docs.github.com/en/graphql/overview/explorer. To me it makes sense that the variables that should go together are next to each other

2021-05-28 14:25 UTC, pergaliuke commented on src/schema/resolvers/animal.ts
> +                limit != null ? limit + 1 : limit,
disagree, the result would be different then limit is 0

2021-05-28 15:27 UTC, pergaliuke commented on src/schema/typeDefs/animal.graphql
> +        after: String,
I haven't changed this one yet. AzisK point looks very convincing.

2021-05-30 08:14 UTC, ignasposka commented on src/schema/typeDefs/animal.graphql
> +        after: String,
Alright, I don't have a strong preference about this. If you say it's not more clear, let's leave it as it is.

2021-05-30 08:16 UTC, ignasposka commented on src/schema/resolvers/animal.ts
> +                limit != null ? limit + 1 : limit,
Good catch!

2021-05-30 08:27 UTC, ignasposka approved these changes
Impressive work 👏 Thank you!

2021-05-30 09:00 UTC, ignasposka commented
@pergaliuke Looks like there is a TS error in `favoriteAnimal.ts` file after updating branch. Can you take a look?

2021-05-30 14:29 UTC, AzisK commented on src/schema/resolvers/animal.ts
> +                limit != null ? limit + 1 : limit,
Do you think it's worth writing a test for such case?

2021-05-31 08:45 UTC, merged