#228_Create_resolver_for_app_user
pets-oss/pets-back pull request #254
Opened 2021-05-28 18:25 UTC by pergaliuke

Not finished, wanted to check solution would be good enough. As well I hoped to use inheritResolversFromInterfaces, but it doesn't work as I expected.

2021-05-30 18:08 UTC, pergaliuke commented
Error output is not being shown in docker logs #240.
addResolversToSchema handles schema validation, errors are visible in docker logs. For example.
![image](https://user-images.githubusercontent.com/48152843/120114985-68090000-c18a-11eb-90f8-130f2083d107.png)

2021-05-31 16:49 UTC, AzisK requested changes
Maybe we should not return all the information but otherwise it looks good to me.

Left a few comments and questions

2021-05-31 16:49 UTC, AzisK commented on src/schema/index.ts
> +        givenAwayEventResolvers,
I see `givenAwayEventResolvers` 2 times

2021-05-31 16:49 UTC, AzisK commented on src/schema/typeDefs/animalRegistration.graphql
> +extend type Query {
Is this part of this issue?

2021-05-31 16:49 UTC, AzisK commented on test/event.graphql.test.ts
> +export const authorFields = `
Maybe this is a good candidate to go into a separate file?

2021-05-31 21:24 UTC, pergaliuke commented on src/schema/typeDefs/animalRegistration.graphql
> +extend type Query {
After I changed to addResolversToSchema, app crashed
![image](https://user-images.githubusercontent.com/48152843/120242974-f8207580-c26e-11eb-8ebe-d20ec31d7f52.png)

I fixed it by adding to schema. But maybe we can remove it from resolvers and from schema if this functionality is not needed anymore.

2021-05-31 21:35 UTC, pergaliuke commented on src/schema/index.ts
> +        givenAwayEventResolvers,
Good catch :)

2021-06-01 11:19 UTC, pergaliuke commented on test/event.graphql.test.ts
> +export const authorFields = `
Done

2021-06-04 08:19 UTC, JustasBelevicius approved these changes

2021-06-04 08:19 UTC, JustasBelevicius commented on src/index.ts
> +                    // response.http.status.set(400);
Well done! One note here: either remove the console statement, or remove the commented out line.

2021-06-04 10:32 UTC, AzisK approved these changes

2021-06-04 10:49 UTC, merged