#245 Create table for medication event details
pets-oss/pets-back pull request #256
Opened 2021-06-02 09:08 UTC by linaskitm

2021-06-03 17:30 UTC, AzisK approved these changes
GJ

2021-06-03 17:38 UTC, AzisK requested changes
Medication event in `events` table is only the third one. Others are not really medication events. You would need to add them in `events` table.
`(3, 'Medical', 'Medication', '2020-05-21', 'dhjbwau74a6', 'Tick medications')`

2021-06-03 17:38 UTC, AzisK commented on database/3-fake-data.sql
> +(1, 'Some pills from Prophylaxis', 20.00),
Medication event in `events` table is only the third one. Others are not really medication events. You would need to add them in `events` table.
`(3, 'Medical', 'Medication', '2020-05-21', 'dhjbwau74a6', 'Tick medications')`

2021-06-07 11:44 UTC, linaskitm commented on database/3-fake-data.sql
> +(1, 'Some pills from Prophylaxis', 20.00),
Sorry for late response.
Now I see why we needed these changes, we will create tables for all `*_event_details`

2021-06-09 11:46 UTC, AzisK approved these changes
GJ

2021-06-09 11:46 UTC, merged