#257 Enhance AnimalConnection
pets-oss/pets-back pull request #258
Opened 2021-06-02 23:44 UTC by pergaliuke

totalCount returns all animals count, and does not consider ids, gender and other 'filters'

2021-06-03 07:15 UTC, AzisK commented on src/sql-queries/animal.ts
> +        (SELECT COUNT(*) FROM ${table}) AS total_count`)
I am thinking that maybe the total count should be filtered by the same filters. WDYT?

2021-06-03 07:19 UTC, AzisK reviewed
I am thinking that maybe the total count (for the filters) should be filtered by the same filters as the usual query. WDYT?

2021-06-04 14:22 UTC, ignasposka commented
Tests are failing can you take a look?

2021-06-04 14:24 UTC, ignasposka requested changes
Looks good, but tests are failing and I'm getting `operator does not exist: gender = integer` while testing locally. Please fix that.

2021-06-05 09:05 UTC, AzisK commented on src/sql-queries/animal.ts
> +        .from(`${table} as a`);
Since `AS` is SQL keyword, we could upper-case it here and in other places as well

2021-06-05 09:22 UTC, AzisK approved these changes

2021-06-05 09:22 UTC, AzisK commented on src/sql-queries/animal.ts
> +    pagination = pagination.crossJoin('total_count');
I am not sure we need this cross join since we can simply select and avoid the join. I don't know if the cross join would affect performance. If yes, I suppose it should not affect significantly (tested locally having 4k+ rows). I am fine with a solution with cross joins as well.

2021-06-05 15:34 UTC, ignasposka approved these changes

2021-06-06 11:54 UTC, pergaliuke commented on src/sql-queries/animal.ts
> +    pagination = pagination.crossJoin('total_count');
I am leaving as it is for now.

2021-06-06 11:55 UTC, merged