Changed database structure
pets-oss/pets-back pull request #43
Opened 2021-01-07 21:07 UTC by JBK91

- Removed `organization` column from `event` tables
- Created `app_user_role` table - one user may have role in more than 1 organisation
- Removed street address slitting from `organization` table - IMO we don't need 3 columns for street address (street, house and flat)
- created `animal_registration` table to store registration data and added `status` column to track if that registration is active
- created `animal_microchip` table to store microchip data and added `status` column to track if that chip is implanted
- created `animal_details` table to split animal general info from `animal` table

2021-01-08 07:38 UTC, JustasBelevicius approved these changes
Well done 👍 ! Since the product is not in production stages yet, it would be better to add all the schema changes to the 1-schema.sql editing the create queries directly. I know it wasn't done like that before, but I believe that would look cleaner until we are forced to do it all with alterations when the app is used.

tl;dr; 
- CREATE and ALTER (just edit table CREATION queries instead) can be moved to the 1-schema.sql
- INSERT queries go to 2-data.sql, it won't be run on production in the later stages of the app.

2021-01-08 08:28 UTC, AzisK approved these changes
Good job!

2021-01-08 08:30 UTC, AzisK commented
> Well done 👍 ! Since the product is not in production stages yet, it would be better to add all the schema changes to the 1-schema.sql editing the create queries directly. I know it wasn't done like that before, but I believe that would look cleaner until we are forced to do it all with alterations when the app is used.

We can do this with a separate pull request since this approach is already used before

2021-01-08 15:48 UTC, psaulenas requested changes
You need also update GraphQL schema

2021-01-08 15:48 UTC, psaulenas commented on database/4-change_structure.sql
> +ALTER TABLE animal
Please update also https://github.com/pets-oss/pets-back/blob/main/src/schemas/animal.ts#L28

2021-01-11 06:31 UTC, ignasposka requested changes
I'm not sure what we are doing with animal type in GraphQL side. At this point I see removing lot of fields from animal type, but they still somehow should be available through GQL endpoint, what's the plan for that?

2021-01-11 06:31 UTC, ignasposka commented on database/4-change_structure.sql
> +ALTER TABLE animal
Why animal GQL schema should be updated? I think it should remain the same for the user of GQL endpoint 🤔

2021-01-11 07:18 UTC, JBK91 commented on database/4-change_structure.sql
> +ALTER TABLE animal
`created animal_registration table to store registration data and added status column to track if that registration is active
created animal_microchip table to store microchip data and added status column to track if that chip is implanted`

in the rare case microchips can be changed (damaged or something), registrations too. With these tables we will have historical data for animal. If that data will be only in animal where can be only one value, we lose historical data.

`animal_details` is to split general info/details from `animal` table

2021-01-11 09:15 UTC, JBK91 commented
> I'm not sure what we are doing with animal type in GraphQL side. At this point I see removing lot of fields from animal type, but they still somehow should be available through GQL endpoint, what's the plan for that?

I am not sure what needs for that, if frontend needs to have all data calling `animal`, than I will update animal query to include other related data, in other cases I will add endpoints.

IMO: `animal_details` could be in `animal` endpoint:
{
   animal {
         ....,
         details {
              ....
         }
   }
}

other (microchips and registrations) other endpoints

2021-01-11 17:02 UTC, ignasposka commented
> > I'm not sure what we are doing with animal type in GraphQL side. At this point I see removing lot of fields from animal type, but they still somehow should be available through GQL endpoint, what's the plan for that?
> 
> I am not sure what needs for that, if frontend needs to have all data calling `animal`, than I will update animal query to include other related data, in other cases I will add endpoints.
> 
> IMO: `animal_details` could be in `animal` endpoint:
> {
> animal {
> ....,
> details {
> ....
> }
> }
> }
> 
> other (microchips and registrations) other endpoints

I think we could have GQL query `Animal` which would let to get animal with all microchips, details and registrations. This is the one of the main GQL feature, to let GQL client choose exactly what it wants. It would be silly to not use this advantage of GQL. In my opinion `Animal` query would look like the following:


```
{
    Animal {
        name,
        animal_details {
            color
        },
        animal_registration {
            status
        }
    }
}
```

2021-01-12 14:12 UTC, ignasposka approved these changes
Good to go, but please fix animal query after merging this.

2021-01-12 14:23 UTC, psaulenas approved these changes
Overall looks good, you missed to remove few columns from one query

2021-01-12 14:23 UTC, psaulenas commented on src/sql-queries/animal.ts
>                      registration_date,
You missed to remove `registration_no` and `registration_date`

2021-01-12 17:36 UTC, merged