CORS policy
pets-oss/pets-back pull request #44
Opened 2021-01-08 14:17 UTC by tautvydasr

Add CORS policy without it GQL front client request will be blocked.

2021-01-08 14:19 UTC, AzisK approved these changes
LG

2021-01-08 14:24 UTC, psaulenas approved these changes

2021-01-11 06:52 UTC, ignasposka requested changes
There are some doubts about CORS. @JBK91 showed that allowing CORS could result into performance issues: ttps://www.freecodecamp.org/news/the-terrible-performance-cost-of-cors-api-on-the-single-page-application-spa-6fcf71e50147/ and https://blog.bitsrc.io/how-and-why-you-should-avoid-cors-in-single-page-apps-db25452ad2f8.
We can use api.petbook.lt subomain for an api, would that help to avoid allowing CORS?

2021-01-11 16:01 UTC, ignasposka approved these changes
Alright, so I think in slack chat we have decided that CORS policy is not that performance killer in our case, as our API has a single endpoint and it requires single OPTIONS request which can be cached by a browser for a relatively long time.

2021-01-12 12:59 UTC, merged