38 - Add fetch query to get available genders
pets-oss/pets-back pull request #47
Opened 2021-01-11 08:36 UTC by dainius-jankunas

2021-01-11 17:06 UTC, ignasposka approved these changes
Looks good!

2021-01-11 18:38 UTC, AzisK requested changes
Looking good overall. Left a few comments for improvements

2021-01-11 18:38 UTC, AzisK commented on src/schemas/gender.ts
> +    genders(language: 'lt')
Single quoted `'lt'` gives me an error. It is only happy with double quotes `"lt"`
```
{
  genders(language: "lt") {
    id
  }
}
```

2021-01-11 18:38 UTC, AzisK commented on src/sql-queries/gender.ts
> +                WHERE gender = ANY(enum_range(null::gender))
Do we need this WHERE? Enum itself allows only enum values inside, so this additional check is not needed, I would say

2021-01-13 07:18 UTC, dainius-jankunas commented on src/schemas/gender.ts
> +    genders(language: 'lt')
fixing that

2021-01-13 07:19 UTC, dainius-jankunas commented on src/sql-queries/gender.ts
> +                WHERE gender = ANY(enum_range(null::gender))
will remove it

2021-01-13 17:08 UTC, JustasBelevicius approved these changes

2021-01-13 17:14 UTC, AzisK approved these changes
I suppose we should not order genders since we did not order animals. Everything else looks smooth

2021-01-13 17:14 UTC, AzisK commented on src/sql-queries/gender.ts
> +                ORDER BY id;`;
We did not order Animals, so I suppose we should not order Genders as well

2021-01-13 19:21 UTC, merged