updated animal entity
pets-oss/pets-back pull request #50
Opened 2021-01-12 20:58 UTC by JBK91

2021-01-12 21:32 UTC, AzisK approved these changes
Great job

2021-01-12 21:32 UTC, AzisK commented on src/schemas/animal_details.ts
> +type AnimalDetails {
Originally `animal` table in the database had a field called `status` that was meant to describe health of the animal. Now the `animal` still has it but I am wondering where would it be better to have the health 'status'. In animal directly or in animal_details. WDYT?

2021-01-12 21:54 UTC, AzisK commented on src/schemas/animal_details.ts
> +type AnimalDetails {
I also remembered that we should also have status `adopted`. So this could be a separate field or this value could be part of status as well

2021-01-13 08:21 UTC, JBK91 commented on src/schemas/animal_details.ts
> +type AnimalDetails {
IMO `health` and `adopted` or `not adopted` describes different status, so should be separate field

2021-01-13 08:29 UTC, AzisK commented on src/schemas/animal_details.ts
> +type AnimalDetails {
Okay, we can deal with this a little bit later

2021-01-13 17:06 UTC, JustasBelevicius approved these changes

2021-01-13 19:53 UTC, ignasposka commented
I would suggest use camelCase for naming files in TS. https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#filename

2021-01-13 20:24 UTC, ignasposka requested changes
For all data fields which have translations it should be added object containing id and translation. For example:
```
{
    "id": "1",
    "text": "Patinas" 
}
```

For getting gender query is already written https://github.com/pets-oss/pets-back/blob/main/src/schemas/gender.ts maybe it can be reused.

2021-01-13 20:24 UTC, ignasposka commented on src/sql-queries/animal_details.ts
> +    const text = `SELECT
I know it was taken from pg client docs, but maybe it would make more sense to call it somehow different than just "text"? Maybe `sqlQuery`?

2021-01-13 20:24 UTC, ignasposka commented on src/schemas/animal_details.ts
> +  breed_id: Int
It should be breed object containing breed_id and translation. In SQL level you should make a join with `breed_translation` and get translations. This is needed for frontend to receive both id and display value when fetching animal. You can see example of how it's done in https://github.com/pets-oss/pets-back/blob/main/src/schemas/gender.ts

2021-01-13 20:24 UTC, ignasposka commented on src/schemas/animal_details.ts
> +  gender: String,
Same for gender, you can just reuse https://github.com/pets-oss/pets-back/blob/main/src/schemas/gender.ts

2021-01-13 20:24 UTC, ignasposka commented on src/schemas/animal_details.ts
> +  color: Int
Same for colors. Of course breed query is not written yet. It will be written in this ticket https://github.com/pets-oss/pets-back/projects/1#card-52087873
So it's up to you write now or add it later.

2021-01-13 20:59 UTC, AzisK commented on src/sql-queries/animal_details.ts
> +    const text = `SELECT
We have "text" for AnimalQuery, so I believe @JBK91 is staying consistent. We can have this renaming improvement with a separate PR

2021-01-13 21:17 UTC, ignasposka commented on src/sql-queries/animal_details.ts
> +    const text = `SELECT
Alright, let's leave it like this for now.

2021-01-13 22:22 UTC, JBK91 commented on src/schemas/animal.ts
> +    details: async ({ id }, __, { pgClient }) => {
That for animal table and it has `details: AnimalDetails` this query is to get AnimalDetails from animal_details table and it has different params. It takes animal entity as first param, query in `animal_details.ts` takes id from second param from request

2021-01-13 22:24 UTC, JBK91 commented on src/schemas/animal_details.ts
> +  breed_id: Int
as there is no queries for breed and gender and there is different task for it, and it should be done with other task IMO

2021-01-13 22:29 UTC, JBK91 commented on src/schemas/animal_details.ts
> +  color: Int
For ideal we should started task from that queries which don't depend on other and then take others when all depended queries exists. But at this moment IMO we should add dependencies in existing queries when writing these queries in separate tasks, and not in one PR, as animal entity is largest

2021-01-14 08:06 UTC, ignasposka approved these changes
It turns out we cannot reuse "get all available genders" query in animal entity. Therefore I agree that these fields detalization should be done in another PR.

2021-01-14 11:38 UTC, merged