39 - Add fetch query to get available statuses
pets-oss/pets-back pull request #53
Opened 2021-01-14 18:27 UTC by dainius-jankunas

2021-01-14 20:25 UTC, ignasposka requested changes
Good job, but I think contents of the result should be validated in test.

2021-01-14 20:25 UTC, ignasposka commented on test/status.graphql.test.ts
> +describe('GraphQL integration tests', () => {
I would suggest to call this "Getting statuses" or something more specific.

2021-01-14 20:25 UTC, ignasposka commented on test/status.graphql.test.ts
> +                expect(statuses).to.have.lengthOf(4);
Why don't you validate contents of result? I think we should check that.

2021-01-14 20:51 UTC, AzisK approved these changes
Good and fast job, left a few comments about possible improvements

2021-01-14 20:51 UTC, AzisK commented on database/1-schema.sql
> +INSERT INTO status_translation (status, language, translation) VALUES
I believe it's good to separate insertions to the 2-data file because it's easier to understand the schema when there are only table creations in this file

2021-01-14 20:51 UTC, AzisK commented on test/status.graphql.test.ts
> +                expect(statuses).to.have.lengthOf(4);
Yes, there is an example (animal) of how to do that easily. Also "Test" part "C.i. Validate data with interfaces" in README should help you to understand the context and how to validate with interface

2021-01-14 20:51 UTC, AzisK commented on test/status.graphql.test.ts
> +        {statuses(language: "lt") {
Minor, but the alignment makes it a little hard to read

2021-01-14 20:54 UTC, AzisK requested changes
Agree that we should validate the content of GraphQL

2021-01-14 22:22 UTC, JBK91 commented on database/1-schema.sql
> +    status status,
IMO status, language and translation should have constraint NOT NULL. There is no benefit for having NULL in any of these fields

2021-01-15 12:34 UTC, AzisK approved these changes

2021-01-17 20:22 UTC, ignasposka approved these changes

2021-01-18 09:48 UTC, merged