finished animal and added tests
pets-oss/pets-back pull request #64
Opened 2021-01-17 01:38 UTC by JBK91

- Added color, breed and species queries and schemas
- Added tests for every query
- Changed tests folder structure

P.S. Sorry for large PR, it is last time

2021-01-17 18:16 UTC, AzisK approved these changes
Good job, this covers a lot of functionality. I was wondering if you wrote those validators yourself? Not using `typescript-json-validator`? I left few comments for possible improvements

2021-01-17 18:16 UTC, AzisK commented on test/interfaces/animal.interface.ts
> +  status: string | null,
We could go and be even more specific by choosing an enum value here ('Implanted' or 'Removed'). This could be done in Graphql query layer as well

2021-01-17 18:48 UTC, JBK91 commented on test/validators/animal.interface.validator.ts
> +import { inspect } from 'util';
yes, `typescript-json-validator` generates not used code and imports are strange

2021-01-18 10:09 UTC, AzisK commented on test/validators/animal.interface.validator.ts
> +import { inspect } from 'util';
Okay, that makes sense but I would prefer us simply using it because correcting them we add more work and maintenance for us (2 places for data types). If we happen to change the interface, we cannot simply regenerate the validator, we will need additional work and potentially have more places to have bugs in.

Actually interface is not needed if we write validators. `typescript-json-validator` generates validator out of interface.

RE: "generates not used code and imports are strange". I understand this is not very good for having clean code structure but given that this code is generated and not used in production (only for testing), I would this is not as important. We also know that it works right. Now when I think of it, actually some of these validators could be reused later for data validation, so it might be used in production.

2021-01-18 10:15 UTC, JBK91 commented on test/validators/animal.interface.validator.ts
> +import { inspect } from 'util';
Why we can't simply regenerate? delete old -> generate won't work?

2021-01-18 10:16 UTC, AzisK commented on test/validators/animal.interface.validator.ts
> +import { inspect } from 'util';
We can but are we then going to get rid of not used code and fix the imports by hand?

2021-01-18 11:43 UTC, JBK91 commented on test/validators/animal.interface.validator.ts
> +import { inspect } from 'util';
Maybe it is not necessary, I just cleaned for clean code

2021-01-18 12:03 UTC, AzisK commented on src/sql-queries/breed.ts
> +        LEFT JOIN breed_translation bt ON bt.breed = b.id
Would it be possible to join only when species is asked for?

2021-01-19 08:07 UTC, ignasposka requested changes
Whoa, that was huge PR. Good job! 
Still, I think that `animalDetails`, `animalMicrochips` and `animalRegistrations` queries shouldn't be exposed standalone. All three of these make sense in context of an animal, so they should be nested only in animal entity. By this nesting we empowering big feature of GQL - "Get many resources
in a single request".

2021-01-19 08:36 UTC, AzisK commented on src/sql-queries/breed.ts
> +        LEFT JOIN breed_translation bt ON bt.breed = b.id
I think we have a join to get species next to breed. Is that right? @JBK91

2021-01-19 08:36 UTC, AzisK commented on src/schemas/animalDetails.ts
> +            if (!dbResponse.rows[0]) {
Genders have only four values but we have the same approach for breed, species, color and maybe something else. We are fine as long as we are only dealing with Lithuanian language. As for performance, I suppose it won't be a very hard query to have `WHERE language IN ('lt', 'en')` but I agree it adds some weight. We can go both ways

2021-01-20 12:40 UTC, ignasposka approved these changes

2021-01-20 12:44 UTC, merged