add authorization to api
pets-oss/pets-back pull request #78
Opened 2021-01-26 11:25 UTC by povkas

Will need to add environment variables to the readme

2021-01-27 17:44 UTC, JBK91 requested changes
Tests are red

2021-01-27 17:44 UTC, JBK91 commented on src/index.ts
> +var jwt = require('express-jwt');
use ES6 syntax (let, const instead of var). Also imports also could be ES6. In this case:
`import { jwt } from 'express-jwt';`

2021-01-27 17:44 UTC, JBK91 commented on src/index.ts
> +      jwksUri: process.env.AUTH0_DOMAIN + '.well-known/jwks.json'
Could use template literal. ``${process.env.AUTH0_DOMAIN}.well-known/jwks.json``

2021-01-31 10:50 UTC, ignasposka commented
> Will need to add environment variables to the readme

Maybe it is good idea to disable auth for local/dev env?

2021-02-20 12:53 UTC, JBK91 approved these changes

2021-02-20 12:53 UTC, JBK91 commented on src/getBearerToken.ts
> +// axios here is only for testing purposes
do we need 2 identical files? `getBearerToken.ts` and `src/getBearerToken.ts `?

2021-02-20 16:35 UTC, AzisK approved these changes

2021-02-20 16:35 UTC, AzisK commented on getBearerToken.ts
> +        client_id: process.argv[3],
Would be clearer to access named arguments

2021-02-20 21:00 UTC, ignasposka commented on src/getBearerToken.ts
> +// axios here is only for testing purposes
Good catch. One file should be eliminated.

2021-02-20 21:40 UTC, merged