77 - add mutation for animal microchip
pets-oss/pets-back pull request #84
Opened 2021-02-05 15:04 UTC by dainius-jankunas

no tests yet

2021-02-06 15:42 UTC, AzisK approved these changes
Looks good, left one comment. It would be good to add tests as well

2021-02-06 15:42 UTC, AzisK commented on src/schema/typeDefs/animalMicrochip.graphql
> +input CreateImplantedAnimalMicrochipInput {
Maybe no need for `UpdateImplantedAnimalMicrochipInput` and `CreateImplantedAnimalMicrochipInput` since they are the same?

2021-02-07 10:27 UTC, ignasposka requested changes
Good job, but please add tests.

2021-02-07 10:27 UTC, ignasposka commented on src/schema/typeDefs/animalMicrochip.graphql
> +input CreateImplantedAnimalMicrochipInput {
Create input object should come without id, because id is being selected by API for a new object.

2021-02-07 18:32 UTC, JBK91 commented on src/schema/typeDefs/animalMicrochip.graphql
> +input CreateImplantedAnimalMicrochipInput {
What cases are where would need change id manually?

2021-02-13 15:38 UTC, ignasposka approved these changes
👌

2021-02-13 16:39 UTC, merged