Mutations for animal registration
pets-oss/pets-back pull request #85
Opened 2021-02-06 15:34 UTC by AzisK

2021-02-07 19:47 UTC, ignasposka requested changes
I think some changes are needed.

2021-02-07 19:47 UTC, ignasposka commented on test/animalRegistration.graphql.test.ts
> +            animalId: 6,
We shouldn't let choose id for API user, because ids are just auto-incremented.

2021-02-07 19:47 UTC, ignasposka commented on test/animalRegistration.graphql.test.ts
> +    it ('Update animal_id=3 registration', (done) => {
Maybe you can add option when not all fields are present?

2021-02-07 19:53 UTC, AzisK commented on src/sql-queries/animalRegistration.ts
> +export const undeleteAnimalRegistrationQuery = (input: AnimalRegistrationInput): QueryConfig =>
I imagined a case when we delete a `registrationNo` for an animal and yet later want to add it. It would be impossible to do so because of the primary key restriction. Then this `undeleteAnimalRegistrationQuery` is used. It is also not exposed to API, this is only internal as part of `createAnimalRegistration`

2021-02-07 19:57 UTC, AzisK commented on src/schema/resolvers/animalRegistration.ts
> +      if (isAnimalRegistration.rows[0] && isAnimalRegistration.rows[0].delete_time) {
It checks whether the registration is deleted. If yes, it undeletes it. Otherwise it creates a new one

2021-02-07 20:01 UTC, AzisK commented on test/animalRegistration.graphql.test.ts
> +            animalId: 6,
I think it's fine to have here since the user can know the animal id. How else can we create a registration for a specific animal id without passing it?

2021-02-07 20:02 UTC, AzisK commented on test/animalRegistration.graphql.test.ts
> +    it ('Update animal_id=3 registration', (done) => {
I could add such a case though I want to say that we should be thoughtful when creating tests because tests have a maintenance price as well

2021-02-07 20:08 UTC, JBK91 commented on database/1-schema.sql
> +    registration_date DATE DEFAULT CURRENT_DATE,
registration date is when animal had registration, not when we added in our database

2021-02-07 20:12 UTC, AzisK commented on database/1-schema.sql
> +    registration_date DATE DEFAULT CURRENT_DATE,
I understand that and I believe it should be sent together but imagine a case when the API user forgets to send the registration_date. Then at least this default mechanism sets it to the day it is added

2021-02-08 07:06 UTC, JBK91 commented on database/1-schema.sql
> +    registration_date DATE DEFAULT CURRENT_DATE,
But if API user forgets send animal name we don't set it to default name. Also registration_date can't be null, so there should be validation in frontend

2021-02-08 20:14 UTC, ignasposka commented on src/schema/resolvers/animalRegistration.ts
> +      if (isAnimalRegistration.rows[0] && isAnimalRegistration.rows[0].delete_time) {
I don't think we should let bring back to life deleted objects so easily. You should inform user that object is deleted and if user really wants to undelete it, he/she will do that action explicitly.

2021-02-08 20:15 UTC, ignasposka commented on test/animalRegistration.graphql.test.ts
> +            animalId: 6,
Sorry, I missed the point here.

2021-02-08 20:17 UTC, ignasposka commented on test/animalRegistration.graphql.test.ts
> +    it ('Update animal_id=3 registration', (done) => {
Alright, that's up to you to decide then. It was just a suggestion.

2021-02-08 20:18 UTC, ignasposka commented on database/1-schema.sql
> +    registration_date DATE DEFAULT CURRENT_DATE,
Isn't animal having registered when we add it to our database?

2021-02-08 22:17 UTC, AzisK commented on database/1-schema.sql
> +    registration_date DATE DEFAULT CURRENT_DATE,
I don't know if name is a good comparison but I get the point. We do not have registration date `NOT NULL`. However, we can add it. If we do not have it in the database, I think the system would be more robust if we have this default value. I believe we can let the user decide - either go with the default value or change it to whatever he prefers

2021-02-09 08:36 UTC, ignasposka commented on database/1-schema.sql
> +    registration_date DATE DEFAULT CURRENT_DATE,
Yes, I would agree to set current date when registration date is not specified. It is mostly true, that animal is being registered when record is being added to the system.

2021-02-10 18:54 UTC, AzisK commented
Updated according to discussions

Moreover, we are able to have multiple registrations for animal (according to database restrictions). Therefore, I made it to return the last (by registration date) active registration with an animal by default and created a separate query to get all the registrations of an animal (by id)

2021-02-11 11:42 UTC, ignasposka requested changes

2021-02-11 11:42 UTC, ignasposka commented on src/schema/typeDefs/animalRegistration.graphql
> +  registrationNo: String!
I don't quite get why we need to have `newRegistrationNo`. If  `registrationNo` is provided - we update this field, otherwise not.

2021-02-11 11:42 UTC, ignasposka commented on src/sql-queries/animalRegistration.ts
> +export const getActiveLastAnimalRegistrationQuery = (id: number): QueryConfig => {
I don't think we should let have more than one active registration at once for animal.

2021-02-11 20:23 UTC, ignasposka approved these changes
GJ!

2021-02-11 20:23 UTC, ignasposka commented on src/sql-queries/animalRegistration.ts
> +                RETURNING
Is it going return just nulls? (Because data is deleted)

2021-02-11 20:23 UTC, ignasposka commented on test/animalRegistration.graphql.test.ts
> +    const dateIntString = new Date("2021-01-01").getTime().toString();
Did you want to name it "In" instead of "Int"?

2021-02-11 20:23 UTC, ignasposka commented on database/1-schema.sql
>      registration_no VARCHAR(256) NOT NULL,
Maybe mark this as UNIQUE?

2021-02-11 20:26 UTC, AzisK commented on test/animalRegistration.graphql.test.ts
> +    const dateIntString = new Date("2021-01-01").getTime().toString();
I wanted Int. It is the date integer but I turn it to string

2021-02-11 20:26 UTC, AzisK commented on src/sql-queries/animalRegistration.ts
> +                RETURNING
It returns the deleted animal data

2021-02-11 22:02 UTC, merged