Applied nested mutation for animal
pets-oss/pets-back pull request #88
Opened 2021-02-13 16:14 UTC by ignasposka

As nested optional fields are one of the GQL advantages, `animalRegistration` mutation can be done inside animal mutation.
By this we have more integral data and we don't have to treat both entities separately.

2021-02-13 18:39 UTC, AzisK requested changes
Please take care of test for this to pass. Also left some comments.
It's definitely useful having this approach. However, we lose the ability to change / create registration separately from the animal. We need to send the whole animal mutation to just create the registration. I believe it would be good to have this possibility separately as well

2021-02-13 18:39 UTC, AzisK commented on src/schema/typeDefs/animalRegistration.graphql
> +  updateAnimalRegistration(input: AnimalRegistrationInput!): AnimalRegistration
registrationNo should not be a necessary field for update

2021-02-13 18:39 UTC, AzisK commented on src/sql-queries/animalRegistration.ts
> +    .   toParams();
Typo

2021-02-13 18:39 UTC, AzisK commented on test/animal.graphql.test.ts
> +          console.log(res.body);
I believe we should get rid of these

2021-02-13 18:39 UTC, AzisK commented on test/animal.graphql.test.ts
> +          console.log(res.body);
They could stay though

2021-02-13 18:39 UTC, AzisK commented on test/validators/animal.interface.validator.ts
> +      `${ajv.errorsText(isAnimal.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Animal'})
I suggest not to change these parts by hand

2021-02-13 18:39 UTC, AzisK commented on package.json
> +    "testSpecific": "mocha -r ts-node/register",
Maybe "test*" would be shorter

2021-02-16 10:04 UTC, ignasposka commented
> Please take care of test for this to pass. Also left some comments.
> It's definitely useful having this approach. However, we lose the ability to change / create registration separately from the animal. We need to send the whole animal mutation to just create the registration. I believe it would be good to have this possibility separately as well

I don't think that there is a point of creating animal registration without animal itself. That even wouldn't be possible, because animal registration requires animal id.

2021-02-16 10:07 UTC, ignasposka commented on test/validators/animal.interface.validator.ts
> +      `${ajv.errorsText(isAnimal.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Animal'})
I just ran generator again on this to update validator.

2021-02-16 10:47 UTC, ignasposka commented on package.json
> +    "testSpecific": "mocha -r ts-node/register",
Star is being ignored in this case, so I cannot use such name.

2021-02-16 11:35 UTC, AzisK commented
> > Please take care of test for this to pass. Also left some comments.
> > It's definitely useful having this approach. However, we lose the ability to change / create registration separately from the animal. We need to send the whole animal mutation to just create the registration. I believe it would be good to have this possibility separately as well
> 
> I don't think that there is a point of creating animal registration without animal itself. That even wouldn't be possible, because animal registration requires animal id.

I meant rather the request JSON (knowing animal id), I'll ask front-end how do they imagine these things

2021-02-16 11:37 UTC, AzisK approved these changes

2021-02-16 12:55 UTC, merged